import all the libraries and packages


In [1]:
#importin all the related packages nad framework

import pandas as pd
import tensorflow as tf
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn import preprocessing


In [7]:
#geting the data and preparing the data

#loading data
iris_data = pd.read_csv('G:\projects\multiclass_classification_iris\data\iris.csv')

print("data before numeric conversion \n", iris_data.head())

#using label encoder to convert the string to numeric values 

label_encoder = preprocessing.LabelEncoder()
iris_data['Species']= label_encoder.fit_transform(iris_data['Species'])

#converting string to numpy array 
train_data = iris_data.to_numpy()

#separting features and labels
features = train_data[:,0:4]
label = train_data[:,4]

#displaying the features 
print("data after the numeric conversion \nfeatures \n" , features[:5,:])

#displaying the labels 
print("labels \n", label[:5])


data before numeric conversion 
    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
data after the numeric conversion 
features 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
labels 
 [0. 0. 0. 0. 0.]
